version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      
      # Install Ruby dependencies from the Gemfile.
      - bundle install

  pre_build:
    commands:
      # Set the SECRET_KEY_BASE environment variable for running tests
      - export SECRET_KEY_BASE=$(rake secret)

      # Run the tests using RSpec.
      - rake db:migrate RAILS_ENV=test && rspec spec

artifacts:
  type: zip
  files:
    - '.ebextensions'
    - 'config.ru'
    - 'Gemfile'
    - 'README.md'
    - 'Rakefile'
    - 'app/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
