# config/database.yml

default: &default
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  database: bnativus_development

test:
  <<: *default
  database: bnativus_test

production:
  <<: *default
  database: bnativus_production